### ISSUE TITLE
Allow URI connection

### ISSUE THREAD

**Issue by nicolataddei94** [dotnetcore/CAP#355] opened 2019-06-20 09:28 UTC
Sometimes it would be convenient to be able to connect directly with the uri.

Like:

`private static string url = ConfigurationManager.AppSettings["CLOUDAMQP_URL"];
static readonly ConnectionFactory connFactory = new ConnectionFactory();
connFactory.Uri = new Uri(url.Replace("amqp://", "amqps://"));`

**Comment by yang-xiaodong** [comment] 2019-06-20 12:45
Hello, we have improved RabbitMQOptions to provide extensions option to configure the client original configuration, you can see at https://github.com/dotnetcore/CAP/issues/350#issuecomment-501946857

**Comment by yang-xiaodong** [comment] 2019-06-20 12:46
duplicate of #350

**Closed by yang-xiaodong** 2019-06-20 12:46 UTC
Labels: duplicate
