### ISSUE TITLE
[Redis streams] When the consumer fails to execute, the retry will stop after three times

### ISSUE THREAD

**Issue by fanslead** [dotnetcore/CAP#928] opened 2021-07-02 08:59 UTC
When you use a RedisStream, you subscribe to an exception for an null object reference, retry three times directly, and the subsequent retries will be consumed successfully.  
The Debug breakpoint cannot enter the corresponding subscribed Service during debugging.  
This is not the case when using other queues.  
Cap.RedisStram handles exceptions internally.  

使用RedisStream时，订阅报异常空对象引用，retry次数直接3次，后续重试会依次成功消费。
调试时Debug断点无法进入对应订阅的Service。
在使用其他队列时没有这种情况。
判断应该是Cap.RedisStram内部处理异常。

**Comment by yang-xiaodong** [comment] 2021-07-02 09:24
Please describe your issue in English. Our Redis Stream contributor are from English-speaking countries

**Comment by yang-xiaodong** [comment] 2021-07-03 10:57
Hello @fanslead ,

Actually, Your question is when an exception occurs in the execution of the subscription method, after three retries, the retry is stop ? Is it right?

**Comment by fanslead** [comment] 2021-07-03 11:10
> Hello @fanslead ,
> 
> Actually, Your question is when an exception occurs in the execution of the subscription method, after three retries, the retry is stop! Is it right?

no, I can't actually catch exceptions. When I debug, the program does not enter a breakpoint.Only the record of execution failure can be seen in the dashboard.

**Comment by yang-xiaodong** [comment] 2021-07-03 11:13
So your question is that Visual Studio cannot hit the breakpoint?

**Comment by fanslead** [comment] 2021-07-03 11:15
even I direct reference source code to debug,only the successful subscription method can enter the breakpoint.

**Comment by yang-xiaodong** [comment] 2021-07-03 12:02
This shows that an exception has occurred in the parameter of the constructor. Please make sure that the message you publish can be converted to the parameter type of the consumer normally.

You can run our example to debug to investigate the cause

**Comment by fanslead** [comment] 2021-07-03 12:17
Please let me describe it in Chinese.I don't know how to describe it in English. 
我发布的参数确定是可以给订阅者接收的类型，因为是同一个类，而且，订阅方法执行失败不是必然情况，他也会有执行成功的情况，当执行失败后，手动重试或者等待第四次自动重试时可以执行成功。
当我换了消息队列组件之后，执行一个失败都没有。
当我引用源码调试时，在执行mysql插入更新操作和cap-exception内容赋值的地方断点，都无法进入，只有在消息执行成功时才能进入到mysql插入语句的断点。异常的时候完全捕获不到，甚至我修改cap-exception内容赋值的地方尝试把异常堆栈内容一起写入，但是并没有生效。

**Comment by yang-xiaodong** [comment] 2021-07-06 07:30
Hello @fanslead ,

We can't reproduce your issue. we recommended to use our example(Samples.Redis.Sqlserver) for testing.  If  you can  reproduced, please provide steps reproduce to us.

Thank you for your feedback, I close this issue now

**Closed by yang-xiaodong** 2021-07-06 07:30 UTC

**Comment by fanslead** [comment] 2021-07-12 03:28
I guess I figured it out. the redis version is 5.0.10 in windows. when i use de redis 6.x in docker, it work. maybe the redis for windows  is not work. @yang-xiaodong It is recommended that you add this question to the document
