### ISSUE TITLE
When RabbitMQ is reconnected due to network reasons, there is a probability will not be reconnect

### ISSUE THREAD

**Issue by xzstudio** [dotnetcore/CAP#1178] opened 2022-07-25 12:22 UTC
Hello, we have a problem in using RabbitMQ as the queue. When the RabbitMQ reconnected due to network reasons and the reconnection action is failed, there is a probability will not be reconnect.

Version：DotNetCore.CAP  6.1.0 
Code：
```
services.AddCap(x =>
{
    x.UseEntityFramework<AppDbContext>();
    x.UseRabbitMQ("localhost");
 });

[Route("api/[controller]")]
public class ValuesController : Controller
{
    //  only one subscribe
    [NonAction]
    [CapSubscribe("sample.rabbitmq.mysql")]
    public void Subscriber(DateTime p)
    {
        Console.WriteLine($@"{DateTime.Now} Subscriber invoked, Info: {p}");
    }
}
```

Exception：
```
RabbitMQ.Client.Exceptions.OperationInterruptedException: The AMQP operation was interrupted: AMQP close-reason, initiated by Library, code=541, text='Unexpected Exception', classId=0, methodId=0, cause=System.IO.IOException: Unable to read data from the transport connection: Connection reset by peer.
 ---> System.Net.Sockets.SocketException (104): Connection reset by peer
   at System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 count)
   --- End of inner exception stack trace ---
   at System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.BufferedStream.ReadByteSlow()
   at RabbitMQ.Client.Impl.InboundFrame.ReadFrom(Stream reader, Byte[] frameHeaderBuffer)
   at RabbitMQ.Client.Framing.Impl.Connection.MainLoopIteration()
   at RabbitMQ.Client.Framing.Impl.Connection.MainLoop()
   at RabbitMQ.Client.Impl.SimpleBlockingRpcContinuation.GetReply(TimeSpan timeout)
   at RabbitMQ.Client.Impl.ModelBase.ModelRpc(MethodBase method, ContentHeaderBase header, Byte[] body)
   at RabbitMQ.Client.Framing.Impl.Model._Private_QueueBind(String queue, String exchange, String routingKey, Boolean nowait, IDictionary`2 arguments)
   at RabbitMQ.Client.Impl.ModelBase.QueueBind(String queue, String exchange, String routingKey, IDictionary`2 arguments)
   at RabbitMQ.Client.Impl.AutorecoveringModel.QueueBind(String queue, String exchange, String routingKey, IDictionary`2 arguments)
   at DotNetCore.CAP.RabbitMQ.RabbitMQConsumerClient.Subscribe(IEnumerable`1 topics)
   at DotNetCore.CAP.Internal.ConsumerRegister.<>c__DisplayClass18_1.<Execute>b__2()
```

**Comment by yang-xiaodong** [comment] 2022-07-26 01:06
Hello, 

We cannot get useful information from your description.

Re-connect healthy health checks are triggered every 30 seconds, please show the log that exceeds 2 minutes for us to analyze

If you can reprodu the issue, please provide the steps.

**Comment by xzstudio** [comment] 2022-07-26 03:14
Logs

![log-1](https://user-images.githubusercontent.com/2088242/180905481-e3b5560f-b0d3-42e4-802e-bfb891d79cd5.png)

Exception

![log-2](https://user-images.githubusercontent.com/2088242/180905601-3fcebf68-5986-4d74-a833-d7c1fc87d5b1.png)

Reprodu the issue

1. Code

```
services.AddCap(x =>
{
    x.UseEntityFramework<AppDbContext>();
    x.UseRabbitMQ("localhost");
 });

[Route("api/[controller]")]
public class ValuesController : Controller
{
    //  signle subscribe
    [NonAction]
    [CapSubscribe("sample.rabbitmq.mysql")]
    public void Subscriber(DateTime p)
    {
        Console.WriteLine($@"{DateTime.Now} Subscriber invoked, Info: {p}");
    }
}
```

1. Launch the app and wait for it to be ready
2. Set the breakpoint
![breakpoint](https://user-images.githubusercontent.com/2088242/180907169-2b78e4d1-8277-4d6d-8368-3edde669e098.png)
4. Stop and restart the RabbitMQ server (like network problems)
5. Waiting the breakpoint hit  and hold (step 2 breakpoint)
6. Stop the RabbitMQ server (second time network problems)
7. Continue the breakpoint and we get the Exception
![error](https://user-images.githubusercontent.com/2088242/180914818-2ee51ba5-70b2-4d49-8f33-380a71cfbb97.png)
9. Looks like `_isHealthy` are not set `false`

**Comment by yang-xiaodong** [comment] 2022-07-26 04:34
This is due to the exception produced by artificial blocking, not the connection disconnecting exception generated by the rabbitmq client, so I think this is in line with expected.

We cannot treat all exception as connection errors and set health false.

**Comment by xzstudio** [comment] 2022-07-26 07:08
Hi, the brickpoint just easy produced the error

This logs is production environment errors：
![loogs](https://user-images.githubusercontent.com/2088242/180905481-e3b5560f-b0d3-42e4-802e-bfb891d79cd5.png)

This exception will cause the health check not work and not reconnect RabbitMQ, until the application is restarted manually.

Maby we shoud hand this exception and  reset health when call `client.Subscribe()`  error
````
RabbitMQ.Client.Exceptions.OperationInterruptedException: The AMQP operation was interrupted: AMQP close-reason, initiated by Library, code=541, text='Unexpected Exception', classId=0, methodId=0, cause=System.IO.IOException: Unable to read data from the transport connection: Connection reset by peer.
 ---> System.Net.Sockets.SocketException (104): Connection reset by peer
   at System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 count)
   --- End of inner exception stack trace ---
   at System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.BufferedStream.ReadByteSlow()
   at RabbitMQ.Client.Impl.InboundFrame.ReadFrom(Stream reader, Byte[] frameHeaderBuffer)
   at RabbitMQ.Client.Framing.Impl.Connection.MainLoopIteration()
   at RabbitMQ.Client.Framing.Impl.Connection.MainLoop()
   at RabbitMQ.Client.Impl.SimpleBlockingRpcContinuation.GetReply(TimeSpan timeout)
   at RabbitMQ.Client.Impl.ModelBase.ModelRpc(MethodBase method, ContentHeaderBase header, Byte[] body)
   at RabbitMQ.Client.Framing.Impl.Model._Private_QueueBind(String queue, String exchange, String routingKey, Boolean nowait, IDictionary`2 arguments)
   at RabbitMQ.Client.Impl.ModelBase.QueueBind(String queue, String exchange, String routingKey, IDictionary`2 arguments)
   at RabbitMQ.Client.Impl.AutorecoveringModel.QueueBind(String queue, String exchange, String routingKey, IDictionary`2 arguments)
   at DotNetCore.CAP.RabbitMQ.RabbitMQConsumerClient.Subscribe(IEnumerable`1 topics)
   at DotNetCore.CAP.Internal.ConsumerRegister.<>c__DisplayClass18_1.<Execute>b__2()
````

**Comment by jerviscui** [comment] 2022-07-26 07:37
marked

**Comment by yang-xiaodong** [comment] 2022-07-26 08:21
When the application starts, it will register a subscriber to Rabbitmq Server. If the connection is closed remotely at this time, this exception will appear. Is this the correct description?

I don't think this is an Exception that needs to be specially processed. If the startup process is just closed by the remote server, the exception can be known by the user

**Comment by yang-xiaodong** [comment] 2022-07-26 08:26
@jerviscui  I delete your comments, which may cause anyone to read unfriendly. If you care about this isue, you can click the subscription button, github will remind you

![image](https://user-images.githubusercontent.com/8205994/180960072-220c5d4c-38f5-4090-8b6b-4a17ff9d1407.png)

**Comment by xzstudio** [comment] 2022-07-27 03:43
> When the application starts, it will register a subscriber to Rabbitmq Server. If the connection is closed remotely at this time, this exception will appear. Is this the correct description?
> 
> I don't think this is an Exception that needs to be specially processed. If the startup process is just closed by the remote server, the exception can be known by the user


Thank you for attention this issue.

I have to say, This is not application starting connect RabbitMQ Server error, you can see the logs ,
![logs](https://user-images.githubusercontent.com/2088242/181154395-09ad8522-aa6b-4ea9-b42f-76e83f78196b.png)

So, I think the problem is that during the reconnection process, the RabbitMQ service is successfully connected, but the connection is broken in the subscription regist. and the health check didn't know there was a problem.

**Comment by yang-xiaodong** [comment] 2022-07-28 08:10
> 5. Stop the RabbitMQ server (second time network problems)
> 6. Continue the breakpoint and we get the Exception

Hello @xzstudio ， 

I just debug the code and I can't reproduce by your steps, after the step 5 stops RabbitMQ Server, it will trigger `MqLogType.ConsumerShutdown` event, and set the` _ishealthy `to `false`

https://github.com/dotnetcore/CAP/blob/fc9aa5460cde7142772808e2cb9f098344d1f893/src/DotNetCore.CAP/Internal/IConsumerRegister.Default.cs#L301-L303

**Closed** 2022-08-01 08:02 UTC
Labels: enhancement

**Comment by xzstudio** [comment] 2022-08-02 08:15
sorry, busy days.
you must flow the steps 1-7,  the point is step 1：signle subscribe. and step 4: hold the break point.
I'm pretty sure you can  reproduce the issue.


> > 5. Stop the RabbitMQ server (second time network problems)
> > 6. Continue the breakpoint and we get the Exception
> 
> Hello @xzstudio ，
> 
> I just debug the code and I can't reproduce by your steps, after the step 5 stops RabbitMQ Server, it will trigger `MqLogType.ConsumerShutdown` event, and set the`_ishealthy`to `false`
> 
> https://github.com/dotnetcore/CAP/blob/fc9aa5460cde7142772808e2cb9f098344d1f893/src/DotNetCore.CAP/Internal/IConsumerRegister.Default.cs#L301-L303

**Comment by yang-xiaodong** [comment] 2022-08-04 02:31
I **absolutely** follow the 1-7 to reproduce the issue, Is the event `MqLogType.ConsumerShutdown`  not triggered in your scene?

**Comment by xzstudio** [comment] 2022-08-05 11:50
if the reconnect throw on the `client.Subscribe(topicIds);`, we can't receive `MqLogType.ConsumerShutdown` event, because event register in the `client.Listening(_pollingDelay, _cts.Token);`

https://github.com/dotnetcore/CAP/blob/fc9aa5460cde7142772808e2cb9f098344d1f893/src/DotNetCore.CAP/Internal/IConsumerRegister.Default.cs#L104-L106
