### ISSUE TITLE
Go IndexOutOfRangeException when using InMemoryStorage

### ISSUE THREAD

**Issue by HengzheLi** [dotnetcore/CAP#977] opened 2021-08-19 15:16 UTC
Repro step:
```
while (true)
{
    await capBus.PublishAsync(topic, model);
}
```
消息过期时间设为0秒后过期（应该就是立即过期吧），运行10到15分钟后，收到异常
···
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Collections.Generic.Dictionary`2.set_Item(TKey key, TValue value)
   at DotNetCore.CAP.InMemoryStorage.InMemoryStorage.StoreMessage(String name, Message content, Object dbTransaction)
   at DotNetCore.CAP.Internal.CapPublisher.Publish[T](String name, T value, IDictionary`2 headers)
   at DotNetCore.CAP.Internal.CapPublisher.Publish[T](String name, T value, String callbackName)
   at DotNetCore.CAP.Internal.CapPublisher.<>c__DisplayClass12_0`1.<PublishAsync>b__0()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__277_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
···

刚开始以为是清理过期消息的频率太低（默认5分钟清理一次）使dictionary满了，但把清理的频率调成5秒后还是运行10分钟左右就收到这个异常。查了SO https://stackoverflow.com/questions/15095817/adding-to-a-generic-dictionary-causes-indexoutofrangeexception  找到这个解释，但是没太明白。帖子说使由于并发引起的，但是我的代码里面并没有并发的代码。

**Comment by HengzheLi** [comment] 2021-08-21 03:05
我看InMemoryStorage里面使用的是Dictionary，是不发布消息的线程和清理过期消息的线程产生了并发冲突了

**Comment by yang-xiaodong** [comment] 2021-09-08 01:27
@HengzheLi  Please report your environment and configuration  and versions.

**Comment by yang-xiaodong** [comment] 2021-09-08 02:18
I have reproduced the issue

**Comment by HengzheLi** [comment] 2021-09-08 03:39
So, will the latest version 5.1.4 include this fixing?

**Comment by yang-xiaodong** [comment] 2021-09-08 03:58
No, I will provide the version number containing the fix when the issue is closed

**Comment by HengzheLi** [comment] 2021-09-27 10:22
Has a plan when to release a version with this fixing?

**Comment by yang-xiaodong** [comment] 2021-09-29 06:13
Fixed in v5.4.0

**Closed by yang-xiaodong** 2021-09-29 06:13 UTC
Labels: bug, fixed
