### ISSUE TITLE
cap是否支持延时消息

### ISSUE THREAD

**Issue by conanl5566** [dotnetcore/CAP#776] opened 2021-02-02 06:32 UTC
假设我想指定消息20分钟之后在被消费，cap是否支持

**Comment by yang-xiaodong** [comment] 2021-02-02 06:38
see: https://github.com/dotnetcore/CAP/issues/442#issuecomment-559923552

**Comment by yang-xiaodong** [comment] 2021-02-02 06:40
Duplicate of #665

**Closed by yang-xiaodong** 2021-02-02 06:40 UTC
Labels: duplicate
