### ISSUE TITLE
Unable to cast object of type 'System.Data.SqlClient.SqlConnection' to type 'Microsoft.Data.SqlClient.SqlConnection

### ISSUE THREAD

**Issue by bingowu0708** [dotnetcore/CAP#601] opened 2020-07-06 07:10 UTC
你好，更新至netcore 3.1版本使用SqlServer并用ADO.net进行连接发布消息时报“Unable to cast object of type 'System.Data.SqlClient.SqlConnection' to type 'Microsoft.Data.SqlClient.SqlConnection'.”错误。

var transactionKey = ((SqlConnection) dbTransaction.Connection).ClientConnectionId;

**Comment by yang-xiaodong** [comment] 2020-07-06 08:43
Duplicate of  #570

**Closed by yang-xiaodong** 2020-07-06 08:43 UTC
Labels: duplicate
