### ISSUE TITLE
System.InvalidCastException with concurrent Subscribers

### ISSUE THREAD

**Issue by franribera** [dotnetcore/CAP#484] opened 2020-01-13 14:28 UTC
When CapOptions.ConsumerThreadCount has a value higher than 1, the consumer is throwing System.InvalidCastException. Some threads are working properly but the other ones are crashing an not recovering never. We are simulating a long running consumer with an infinite loop.

This is the stack trace:

`fail: DotNetCore.CAP.Internal.SubscribeDispatcher[0]
      An exception occurred while executing the subscription method. Topic:Test, Id:1216725249559183360
DotNetCore.CAP.Internal.SubscriberExecutionFailedException: Unable to cast object of type 'Newtonsoft.Json.Linq.JObject' to type 'CapSpike.ConsumerB.Message'.
 ---> System.InvalidCastException: Unable to cast object of type 'Newtonsoft.Json.Linq.JObject' to type 'CapSpike.ConsumerB.Message'.
   at lambda_method(Closure , Object , Object[] )
   at Microsoft.Extensions.Internal.ObjectMethodExecutor.<>c__DisplayClass30_0.<WrapVoidMethod>b__0(Object target, Object[] parameters)
   at Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(Object target, Object[] parameters)
   at DotNetCore.CAP.Internal.SubscribeInvoker.ExecuteWithParameterAsync(ObjectMethodExecutor executor, Object class, Object[] parameter)
   at DotNetCore.CAP.Internal.SubscribeInvoker.InvokeAsync(ConsumerContext context, CancellationToken cancellationToken)
   at DotNetCore.CAP.Internal.SubscribeDispatcher.InvokeConsumerMethodAsync(MediumMessage message, ConsumerExecutorDescriptor descriptor, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at DotNetCore.CAP.Internal.SubscribeDispatcher.InvokeConsumerMethodAsync(MediumMessage message, ConsumerExecutorDescriptor descriptor, CancellationToken cancellationToken)
   at DotNetCore.CAP.Internal.SubscribeDispatcher.ExecuteWithoutRetryAsync(MediumMessage message, ConsumerExecutorDescriptor descriptor, CancellationToken cancellationToken)
warn: DotNetCore.CAP.Internal.SubscribeDispatcher[0]
      The 1th retrying consume a message failed. message id: 1216725249559183360`

**Comment by yang-xiaodong** [comment] 2020-01-14 01:11
duplicate of #473

**Closed by yang-xiaodong** 2020-01-14 01:11 UTC
Labels: duplicate

**Comment by franribera** [comment] 2020-01-14 08:02
With 1 subscriber it works properly. With 5 concurrent subscribers, the first one works properly the other 4, it depends. Why do you think this is a duplicated issue from #473 ?

**Comment by yang-xiaodong** [comment] 2020-01-15 12:49
@franribera  Can you reproduce this problem with version `3.0.1-preview-94915444`?
 I can't reproduce your  issue with the latest code

**Comment by franribera** [comment] 2020-01-16 01:05
@yang-xiaodong I've tryied to reproduce with version 3.0.1-preview-94915444 and 3.0.1-preview-95233114. In both cases it is not throwing exceptions anymore, but the behavior with te concurrent subscribers its the same. Only 1 and sometimes 2 subscribers are running concurrently. The other 3 or 4 seem to not be working.

Could you provide us an example? Just the subscriber implementatio to test the concurrency will be enough.

**Comment by yang-xiaodong** [comment] 2020-01-20 02:59
Hello @franribera , I created a new issue #492 to tracking this thread
