### ISSUE TITLE
Sometimes too many warn message

### ISSUE THREAD

**Issue by pccai** [dotnetcore/CAP#967] opened 2021-07-29 09:16 UTC
2021-07-29 16:49:20.7009||WARN|29|DotNetCore.CAP.Internal.ConsumerRegister|RabbitMQ consumer cancelled. --> amq.ctag-a3hIf5t56bbtBbvKOH2NZw|url: |action: 
2021-07-29 16:49:20.7009||WARN|29|DotNetCore.CAP.Internal.ConsumerRegister|RabbitMQ consumer shutdown. --> CONNECTION_FORCED - broker forced connection closure with reason 'shutdown'|url: |action: 
2021-07-29 16:49:36.8534||WARN|4|DotNetCore.CAP.Processor.TransportCheckProcessor|Transport connection is unhealthy, reconnection...|url: |action: 
2021-07-29 16:49:36.8693||WARN|4|DotNetCore.CAP.Processor.InfiniteRetryProcessor|Processor 'DotNetCore.CAP.Processor.TransportCheckProcessor' failed. Retrying...|url: |action: 
2021-07-29 16:49:38.8853||WARN|42|DotNetCore.CAP.Processor.TransportCheckProcessor|Transport connection is unhealthy, reconnection...|url: |action: 

![image](https://user-images.githubusercontent.com/2232794/127465622-67659f46-4901-4f4b-89ac-c0bff4c86111.png)

**Comment by Linc-li** [comment] 2021-07-30 03:24
Hi, 

I have same issue either, how can we solve this issue?

Look forward to your reply.
Thanks,
Linc

**Comment by xiangxiren** [comment] 2021-07-30 09:11
Please provide your environment and configuration. And provide your steps to reproduce.

**Comment by Linc-li** [comment] 2021-08-01 23:28
Device specifications
Device name DESKTOP-H1NUG3A
Processor Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz 2.11 GHz
Installed RAM 16.0 GB (15.8 GB usable)
Device ID D10EA68A-A37A-47C9-AF30-008486FD9ECB
System type 64-bit operating system, x64-based processor
Windows specifications
Edition Windows 10 Pro
Version 21H1
OS build 19043.1110

**Comment by Linc-li** [comment] 2021-08-01 23:31
Reproduce step:

Just leave computer for a while, then screen is locked down, when open the screen, the error occur.

I think this is caused by cosumer show down event,  then health check InfiniteRetryProcessor will go to dead loop to restart the connection of rabbitmq, but in restart logic there is a bug to throw null object exception, then this will never get out of dead loop.

**Comment by yang-xiaodong** [comment] 2021-08-02 01:37
@Linc-li ,  @pccai  Please show your CAP version ?

**Comment by Linc-li** [comment] 2021-08-02 01:46
5.1.2, latest version

**Comment by yang-xiaodong** [comment] 2021-08-02 01:58
@Linc-li The issue #966 you reported with the current issue are different problems. 

We have fixed current issue in version 5.1.2

**Comment by Linc-li** [comment] 2021-08-02 02:10
So #966 is fixed? How about #967?

**Comment by yang-xiaodong** [comment] 2021-08-02 02:26
duplicate of #952

**Closed by yang-xiaodong** 2021-08-02 02:26 UTC
