### ISSUE TITLE
新版，仪表盘 /cap/nodes 报500 

### ISSUE THREAD

**Issue by clayzhangwl** [dotnetcore/CAP#629] opened 2020-08-13 01:34 UTC
其余地址都正常，只要服务菜单点击会报错
fail: Microsoft.AspNetCore.Server.Kestrel[13]
      Connection id "0HM1V4UO3JHI5", Request id "0HM1V4UO3JHI5:0000003B": An unhandled exception was thrown by the application.
System.Collections.Generic.KeyNotFoundException: The given key 'cap.node' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at DotNetCore.CAP.Dashboard.DashboardRoutes.<>c.<.cctor>b__2_8(DashboardContext x)
   at DotNetCore.CAP.Dashboard.RazorPageDispatcher.Dispatch(DashboardContext context)
   at DotNetCore.CAP.DashboardMiddleware.Invoke(HttpContext context)
   at DotNetCore.CAP.Dashboard.GatewayProxy.GatewayProxyMiddleware.Invoke(HttpContext context, DiscoveryOptions discoveryOptions, INodeDiscoveryProvider discoveryProvider)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
fail: Microsoft.AspNetCore.Server.Kestrel[13]
      Connection id "0HM1V4UO3JHI5", Request id "0HM1V4UO3JHI5:00000079": An unhandled exception was thrown by the application.
System.Collections.Generic.KeyNotFoundException: The given key 'cap.node' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at DotNetCore.CAP.Dashboard.DashboardRoutes.<>c.<.cctor>b__2_8(DashboardContext x)
   at DotNetCore.CAP.Dashboard.RazorPageDispatcher.Dispatch(DashboardContext context)
   at DotNetCore.CAP.DashboardMiddleware.Invoke(HttpContext context)
   at DotNetCore.CAP.Dashboard.GatewayProxy.GatewayProxyMiddleware.Invoke(HttpContext context, DiscoveryOptions discoveryOptions, INodeDiscoveryProvider discoveryProvider)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
fail: Microsoft.AspNetCore.Server.Kestrel[13]

**Comment by xiangxiren** [comment] 2020-08-13 03:29
#609

**Comment by yang-xiaodong** [comment] 2020-08-14 04:40
Duplicate of #609

**Closed by yang-xiaodong** 2020-08-14 04:40 UTC
