### ISSUE TITLE
Cap MySQL package conflict

### ISSUE THREAD

**Issue by GeorGeWzw** [dotnetcore/CAP#771] opened 2021-01-20 03:30 UTC
On installation CAP.MySql The package conflict conflicts with the MySQL driver package I am currently using
![image](https://user-images.githubusercontent.com/46982191/105123250-aaeb0500-5b12-11eb-8734-3481e5b29010.png)

**Comment by yang-xiaodong** [comment] 2021-01-20 03:35
Duplicate of #690

**Closed by yang-xiaodong** 2021-01-20 03:35 UTC
