### ISSUE TITLE
If the consumer executes for too long (more than 5 minutes), it will be re-executed

### ISSUE THREAD

**Issue by Angus221** [dotnetcore/CAP#1228] opened 2022-10-27 06:20 UTC
The consumer executes for too long (more than 5 minutes), it will be re-executed；
Is there a setting item to set the timeout period？

**Comment by yang-xiaodong** [comment] 2022-10-27 07:56
Duplicate of #292

This is by design, see https://cap.dotnetcore.xyz/user-guide/en/cap/messaging/#retry

**Closed by yang-xiaodong** 2022-10-27 07:56 UTC
Labels: duplicate
