### ISSUE TITLE
The npgsqldatareader is not closed

### ISSUE THREAD

**Issue by luesheng** [dotnetcore/CAP#712] opened 2020-11-09 07:22 UTC
It is found that there are a large number of idle connections. Finally, the problem is the code. The npgsqldatareader is not closed, forming a lot of idle connections. After connecting to npgsql, the connection needs to be closed, which can effectively release the connection;

**Comment by yang-xiaodong** [comment] 2020-11-09 07:29
Hello,

Can you link to the code or submit a PR?

**Comment by luesheng** [comment] 2020-11-09 07:44
public static T ExecuteReader<T>(this IDbConnection connection, string sql, Func<IDataReader, T> readerFunc,
            params object[] sqlParams)
        {
            if (connection.State == ConnectionState.Closed)
            {
                connection.Open();
            }

            using var command = connection.CreateCommand();
            command.CommandType = CommandType.Text;
            command.CommandText = sql;
            foreach (var param in sqlParams)
            {
                command.Parameters.Add(param);
            }

            using var reader = command.ExecuteReader();

            T result = default;
            if (readerFunc != null)
            {
                result = readerFunc(reader);
            }

            return result;
        }

**Comment by luesheng** [comment] 2020-11-09 09:34
![image](https://user-images.githubusercontent.com/69179372/98513297-984a8900-22a2-11eb-83f6-f68783b1e676.png)

**Comment by xiangxiren** [comment] 2020-11-10 07:23
Hi.
Through my test, there are indeed idle connections, but only a small amount, and will be released after a certain period of time. I also used the optimized code you provided for testing, but the performance is consistent. But the IDataReader object here should really be closed after use. Maybe my test method is different from yours. You can provide your reproduction method, such as specific code, operation steps, etc.

**Comment by cocosip** [comment] 2020-11-12 06:48
We have the same problem!

**Comment by yang-xiaodong** [comment] 2020-11-13 03:36
Hello @luesheng ,

Please describe your problem in detail, because npgsql provides a connection pool, and you can set ConnectionIdleLifetime to try again, I think it's by design.

**Comment by yang-xiaodong** [comment] 2020-11-16 01:46
No response , closed

**Closed by yang-xiaodong** 2020-11-16 01:46 UTC
