### ISSUE TITLE
Can I Define a Consumer Not By CapSubscribe Attribute？

### ISSUE THREAD

**Issue by yb12306** [dotnetcore/CAP#963] opened 2021-07-27 09:25 UTC
Can I Define a Consumer Not By CapSubscribe Attribute？
I want to create a consumer by dynamic

**Comment by mviegas** [comment] 2021-07-27 09:50
Looks like a duplicate of #767 

Please check there.

**Comment by yb12306** [comment] 2021-07-28 09:00
> Looks like a duplicate of #767
> 
> Please check there.

I get it，thanks！

**Closed** 2021-07-28 09:00 UTC
