### ISSUE TITLE
CAP2.6 in .Net Core 3.1 MVC Project

### ISSUE THREAD

**Issue by HuangZhiwei97** [dotnetcore/CAP#488] opened 2020-01-16 01:42 UTC
in my startup.cs,when I use services.AddAutoMapper();Here will has a error.
![Y)in my startup.cs,when I use services.AddAutoMapper();Here will has a error.
EEC0G`$(~P@RIFBHMI0](https://user-images.githubusercontent.com/29914005/72485949-5c8e9080-3844-11ea-80eb-1e644fb6047c.png)

Here is the detail message:
Unable to load one or more of the requested types.
Method 'CommitAsync' in type 'Microsoft.EntityFrameworkCore.Storage.CapEFDbTransaction' from assembly 'DotNetCore.CAP.MySql, Version=2.6.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.

**Comment by yang-xiaodong** [comment] 2020-01-16 06:08
duplicate of #418

**Closed by yang-xiaodong** 2020-01-16 06:08 UTC
Labels: duplicate
