### ISSUE TITLE
Storage init script exception of SqlServer (datetime convert error )

### ISSUE THREAD

**Issue by gnsilence** [dotnetcore/CAP#1302] opened 2023-03-28 03:58 UTC
Local environment is normal.
Error during startup in Linux environment:
![image](https://user-images.githubusercontent.com/18021366/228124496-645a762d-62e7-4d6e-818c-62e841516aa1.png)

**Comment by yang-xiaodong** [comment] 2023-03-28 04:03
Please not use screenshot

**Comment by gnsilence** [comment] 2023-03-28 04:17
> Please not use screenshot

This is Error Code:

[11:51:57 ERR] Initializing the storage structure failed!
Microsoft.Data.SqlClient.SqlException (0x80131904): Conversion failed when converting date and/or time from character string.
   at Microsoft.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at Microsoft.Data.SqlClient.SqlCommand.InternalEndExecuteNonQuery(IAsyncResult asyncResult, Boolean isInternal, String endMethod)
   at Microsoft.Data.SqlClient.SqlCommand.EndExecuteNonQueryInternal(IAsyncResult asyncResult)
   at Microsoft.Data.SqlClient.SqlCommand.EndExecuteNonQueryAsync(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location ---
   at DotNetCore.CAP.SqlServer.DbConnectionExtensions.ExecuteNonQueryAsync(DbConnection connection, String sql, DbTransaction transaction, Object[] sqlParams)
   at DotNetCore.CAP.SqlServer.DbConnectionExtensions.ExecuteNonQueryAsync(DbConnection connection, String sql, DbTransaction transaction, Object[] sqlParams)
   at DotNetCore.CAP.SqlServer.SqlServerStorageInitializer.InitializeAsync(CancellationToken cancellationToken)
   at DotNetCore.CAP.SqlServer.SqlServerStorageInitializer.InitializeAsync(CancellationToken cancellationToken)
   at DotNetCore.CAP.Internal.Bootstrapper.BootstrapAsync(CancellationToken cancellationToken)
ClientConnectionId:b8baffa7-4c5f-466c-a46b-3a5b5df5e1be
Error Number:241,State:1,Class:16
[11:51:57 INF] Starting default Dispatcher
[11:51:57 WRN] We detected that you have duplicate subscribers (updateregister) in same group (group_.cap.queue.hykj.web.entry.v1), this will cause diversity behavior.
[11:51:57 INF] Starting the processing server.
[11:51:57 INF] RabbitMQ consumer registered. --> sgen-1

**Comment by yang-xiaodong** [comment] 2023-03-28 08:03
Hi,
We release a patch preview version `7.1.1-preview-196761499` to nuget a few minutes age. Can you confirm the issue is fixed?

**Comment by gnsilence** [comment] 2023-03-28 08:05
> Hi, We release a patch preview version `7.1.1-preview-196761499` to nuget a few minutes ago. Can you confirm the issue is fixed?

Let me test it out first

**Comment by gnsilence** [comment] 2023-03-28 08:16
> Hi, We release a patch preview version `7.1.1-preview-196761499` to nuget a few minutes ago. Can you confirm the issue is fixed?

There are still errors:

[16:15:18 ERR] Initializing the storage structure failed!
System.Data.SqlTypes.SqlTypeException: SqlDateTime overflow. Must be between 1/1/1753 12:00:00 AM and 12/31/9999 11:59:59 PM.
   at System.Data.SqlTypes.SqlDateTime.FromTimeSpan(TimeSpan value)
   at System.Data.SqlTypes.SqlDateTime.FromDateTime(DateTime value)
   at System.Data.SqlTypes.SqlDateTime..ctor(DateTime value)
   at Microsoft.Data.SqlClient.MetaType.FromDateTime(DateTime dateTime, Byte cb)
   at Microsoft.Data.SqlClient.TdsParser.WriteUnterminatedValue(Object value, MetaType type, Byte scale, Int32 actualLength, Int32 encodingByteSize, Int32 offset, TdsParserStateObject stateObj, Int32 paramSize, Boolean isDataFeed)
   at Microsoft.Data.SqlClient.TdsParser.WriteValue(Object value, MetaType type, Byte scale, Int32 actualLength, Int32 encodingByteSize, Int32 offset, TdsParserStateObject stateObj, Int32 paramSize, Boolean isDataFeed)
   at Microsoft.Data.SqlClient.TdsParser.TDSExecuteRPCAddParameter(TdsParserStateObject stateObj, SqlParameter param, MetaType mt, Byte options, SqlCommand command, Boolean isAnonymous)
   at Microsoft.Data.SqlClient.TdsParser.TdsExecuteRPC(SqlCommand cmd, _SqlRPC[] rpcArray, Int32 timeout, Boolean inSchema, SqlNotificationRequest notificationRequest, TdsParserStateObject stateObj, Boolean isCommandProc, Boolean sync, TaskCompletionSource`1 completion, Int32 startRpc, Int32 startParam)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean isAsync, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry, String method)
   at Microsoft.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, Boolean sendToPipe, Int32 timeout, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry, String methodName)
   at Microsoft.Data.SqlClient.SqlCommand.BeginExecuteNonQueryInternal(CommandBehavior behavior, AsyncCallback callback, Object stateObject, Int32 timeout, Boolean inRetry, Boolean asyncWrite)
   at Microsoft.Data.SqlClient.SqlCommand.BeginExecuteNonQueryAsync(AsyncCallback callback, Object stateObject)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncImpl(Func`3 beginMethod, Func`2 endFunction, Action`1 endAction, Object state, TaskCreationOptions creationOptions)
   at Microsoft.Data.SqlClient.SqlCommand.InternalExecuteNonQueryAsync(CancellationToken cancellationToken)
--- End of stack trace from previous location ---
   at DotNetCore.CAP.SqlServer.DbConnectionExtensions.ExecuteNonQueryAsync(DbConnection connection, String sql, DbTransaction transaction, Object[] sqlParams)
   at DotNetCore.CAP.SqlServer.DbConnectionExtensions.ExecuteNonQueryAsync(DbConnection connection, String sql, DbTransaction transaction, Object[] sqlParams)
   at DotNetCore.CAP.SqlServer.SqlServerStorageInitializer.InitializeAsync(CancellationToken cancellationToken)
   at DotNetCore.CAP.SqlServer.SqlServerStorageInitializer.InitializeAsync(CancellationToken cancellationToken)
   at DotNetCore.CAP.Internal.Bootstrapper.BootstrapAsync(CancellationToken cancellationToken)
[16:15:19 INF] Starting default Dispatcher
[16:15:19 WRN] We detected that you have duplicate subscribers (updateregister) in same group (group_.cap.queue.hykj.web.entry.v1), this will cause diversity behavior.
[16:15:19 INF] Starting the processing server.

**Comment by yang-xiaodong** [comment] 2023-03-28 08:30
What's your sqlserver version?

**Comment by yang-xiaodong** [comment] 2023-03-28 08:36
https://learn.microsoft.com/en-us/sql/t-sql/data-types/datetime2-transact-sql?view=sql-server-ver16

According to the docs, the `datetime2` range is *0001-01-01 through 9999-12-31*

Why your warning is "SqlDateTime overflow. Must be between 1/1/1753 12:00:00 AM and 12/31/9999 11:59:59 PM."

**Comment by gnsilence** [comment] 2023-03-28 08:40
> https://learn.microsoft.com/en-us/sql/t-sql/data-types/datetime2-transact-sql?view=sql-server-ver16
> 
> According to the docs, the `datetime2` range is _0001-01-01 through 9999-12-31_
> 
> Why your warning is "SqlDateTime overflow. Must be between 1/1/1753 12:00:00 AM and 12/31/9999 11:59:59 PM."

My version is  Aliyun RDS SqlServer 2016 Standard edition

**Comment by yang-xiaodong** [comment] 2023-03-28 09:00
Fixed in `7.1.1-preview-196764828`

**Comment by gnsilence** [comment] 2023-03-28 09:08
> 

Thank you. The test is over. No problem.

**Comment by gnsilence** [comment] 2023-03-28 09:27
> Fixed in `7.1.1-preview-196764828`

The startup is fine, but the problem occurs again when subscribing:


`
{
"Headers":
{
"cap-senttime":
"2023/3/28 下午5:21:48",
"cap-callback-name":
null,
"cap-msg-type":
"UpdateRegisterDto",
"cap-msg-name":
"updateregister",
"cap-corr-id":
"19616591236849665",
"cap-corr-seq":
"0",
"cap-msg-id":
"19616591236849665",
"cap-msg-group":
"group_.cap.queue.hykj.web.entry.v1",
"cap-exec-instance-id":
"d9f105a26a30",
"cap-exception":
"SubscriberExecutionFailedException-->Conversion failed when converting date and/or time from character string."
},
"Value":
{
"ordernonumber":
"399274490462277-8972",
"payment_amt":
"1",
"order_id":
"020079910940000772303280007178"
}
}`


By the way, there was nothing wrong with the previous version 6.1

**Comment by gnsilence** [comment] 2023-03-28 09:41
The issue disappeared after a restart, but it is not known if it will appear again, but it is not an emergency issue at the moment

**Comment by gnsilence** [comment] 2023-03-29 01:05
I find that successful ones now require between 1 and 4 retries:

`1640881802563588096
updateregister	group_.cap.queue.hykj.web.entry.v1	1	2023-03-29 09:01:22	2023-03-30 09:01:23

19616595250495491
updateregister	group_.cap.queue.hykj.web.entry.v1	4	2023-03-28 17:42:31	2023-03-29 17:47:08`

**Comment by yang-xiaodong** [comment] 2023-03-29 01:08
You can use our example to see if you can reproduce your issue, if so, please provide steps

**Comment by gnsilence** [comment] 2023-03-29 02:40
> You can use our example to see if you can reproduce your issue, if so, please provide steps

I did not test it out with demo, and I have no problem with it locally. The problem will occur after deploying to linux server. Now I plan to reduce it to version 6.0 first

**Comment by yang-xiaodong** [comment] 2023-03-30 07:10
I can't reproduce this problem in Linux, now I close it.
This may be related to the Chinese culture used by your linux

**Closed by yang-xiaodong** 2023-03-30 07:10 UTC
Labels: bug, fixed
