### ISSUE TITLE
FailedThresholdCallback could not be invoke when the FailedRetryCount value is greater than three

### ISSUE THREAD

**Issue by usama-azakaw** [dotnetcore/CAP#542] opened 2020-04-08 08:40 UTC
FailedThresholdCallback is not getting invoked when the FailedRetryCount value is greater than 3

                x.FailedRetryCount = 10;
                x.FailedRetryInterval = 60;

**Comment by usama-azakaw** [comment] 2020-04-16 06:32
@yang-xiaodong your thoughts ??

**Comment by yang-xiaodong** [comment] 2020-04-16 07:12
I have been busy recently and have not had time to investigate this issue, I will check it this weekend

**Comment by yang-xiaodong** [comment] 2020-04-18 14:20
Hello @usama-azakaw , 

Hello, I cannot reproduce your issue. The fourth (and subsequent) retry is triggered 4 minutes after the message is added to the database. Is the `retries` of the database the same as the `FailedRetryCount` you configured?

**Comment by usama-azakaw** [comment] 2020-04-18 18:54
Hi @yang-xiaodong 

Thanks for your response!

Yes initially at the time of configuration I set the **FailedRetryCount** to 50  , after failing for 50 times I can see the value set to 51 in database but FailedThresholdCallback never gets fired

**Comment by yang-xiaodong** [comment] 2020-04-19 05:00
What caused the failure? publisher or consumer?  Is the type conversion exception or the consumer method call failed?

**Comment by LouieGuo** [comment] 2020-04-22 03:21
I have this problem, too, FailedThresholdCallback could not be invoke  on consumer

**Comment by LouieGuo** [comment] 2020-04-22 03:23
the type conversion exception，such as "SerializationException-->Error converting value"

**Comment by LouieGuo** [comment] 2020-04-22 03:41
sorry . FailedThresholdCallback could be invoke。It's  OK

**Comment by yang-xiaodong** [comment] 2020-04-29 01:49
Missing response, close this issue, please reopen if necessary

**Closed by yang-xiaodong** 2020-04-29 01:49 UTC
