### ISSUE TITLE
connect multiple rabbitmq hosts

### ISSUE THREAD

**Issue by hu-jin-cheng** [dotnetcore/CAP#1129] opened 2022-04-21 02:56 UTC
How to configure and connect multiple rabbitmq hosts?

**Comment by yang-xiaodong** [comment] 2022-04-24 04:41
Duplicate of #264

Please see https://github.com/dotnetcore/CAP/issues/264#issuecomment-451040922

**Closed by yang-xiaodong** 2022-04-24 04:41 UTC
Labels: duplicate, question
