### ISSUE TITLE
Duplicated receive messages

### ISSUE THREAD

**Issue by yavuzsyl** [dotnetcore/CAP#1080] opened 2022-02-04 07:20 UTC
The problem occurs when we publish about 1k messages in a loop. We are publishing one message for each record but the same message is being received more than once.  

Multiple messages are being saved in the cap.received collection, for the same published message that was saved in cap.published collection.  We found that when we put a delay between publishing processes in a loop, received message duplication is being decreased.

We are using, 
Cap.MongoDB to persist queue messages.
Cap version 3.1.22 for publisher and 5.2.0 for subscriber

**Comment by omeerkorkmazz** [comment] 2022-02-04 08:26
@yang-xiaodong,

We noticed the same problem, too. Let me reproduce the problem with details.

We have a cron job that runs in a specified time interval. Basically, there is a `foreach` flow, and each iteration, we do some business and publish messages via `ICapPublisher`. Imagine that there is no concurrent or async publishing process. We recognized that the cap received counts are more than the published ones after an unexpected number of messages were published. What I mean is that not all messages, but, most of the messages are duplicated and processed more than once based on the received or duplicated counts. (e.g., we published 30k messages synchronously, however, 45k messages received)

More interestingly, this issue happens for a large number of messages. 
For instance, we published 100, 200, 500, or 1000 messages sequentially, there was no duplication. However, when we tried to publish 10k 15k, or 30k messages, more than 4-5k messages were duplicated and received more than once.

Here is a list of processes we faced the same issue;
- Single thread foreach flow and sync publishing
- Single thread foreach flow and async publishing
- Parallel foreach and sync publishing
- Parallel foreach and async publishing

**Comment by yang-xiaodong** [comment] 2022-02-06 03:59
Hi,
Possible reason, A large number of messages are placed in the published table. Before they are successfully sent to the Broker, the status is Scheduled. Due to the impact of the sent speed, this process exceeds 4 minutes. When it exceeds 4 minutes, it is picked up by the retry thread and sent again.

**Comment by omeerkorkmazz** [comment] 2022-02-06 11:04
@yang-xiaodong,

Thanks for your explanation. So, here is what all we know; a message is published, placed in the published table, and marked as Scheduled. If a message is sent successfully to the target broker, the sent message is re-marked as Succeeded. We are OK with this process. 

If I understand correctly, you mean that the sending process of messages can exceed 4 minutes due to the sent speed effects (e.g., a large number of messages, network latency, etc.). If the process exceeds a given time, the CAP retries to send a message to the target broker again. It seems that the send-retry mechanism is triggered per 4 minutes. At that moment, something occurs like a race condition, the same message is sent more than once. Is this what we are fronting?

Is there any way to prevent this duplication?

- Locking the message, while sending a broker?
- Increasing the producer thread count so that the process can't exceed 4 minutes? 
- Modifying the exceeding process time for each publisher?

**Comment by yang-xiaodong** [comment] 2022-02-07 01:29
Hi @omeerkorkmazz  

This is a known issue.

1. You may have applied the CAP in the wrong scenario. The outbox mode is not suitable for processing big data scenarios, such as ETL. CAP is mainly suitable for transaction business scenarios in microservices, not data processing.

2. Increasing the number of producer threads can help alleviate this but cannot be avoided, it depends on the processing speed of the database and the broker.

3. In scenarios that need to prevent repetition, it is necessary to ensure idempotency through business rules

**Closed** 2022-02-15 06:39 UTC
Labels: question

**Comment by yang-xiaodong** [comment] 2022-11-23 12:01
We improved this behavior in version 7.0, now default will not pre-fetch to memory to sovle the slow consumer issue.
