### ISSUE TITLE
Unable to cast object of type 'Newtonsoft.Json.Linq.JArray' to type 'System.Collections.Generic.List

### ISSUE THREAD

**Issue by haoas** [dotnetcore/CAP#481] opened 2020-01-10 06:03 UTC
`public class SyncModel
    {
        ............
        public byte[] RowVersion { get; set; }
    }`
**The model can correctly serializer to database ,bu deserializer from db throw  An exception**

 occurred while executing the subscription method. Topic:neworders, Id:1215473106449674240
DotNetCore.CAP.Internal.SubscriberExecutionFailedException: Unable to cast object of type 'Newtonsoft.Json.Linq.JArray' to type 'System.Collections.Generic.List`1[OrderModel.Shared.SyncModel]'.
 ---> System.InvalidCastException: Unable to cast object of type 'Newtonsoft.Json.Linq.JArray' to type 'System.Collections.Generic.List`1[OrderModel.Shared.SyncModel]'.
   at lambda_method(Closure , Object , Object[] )
   at Microsoft.Extensions.Internal.ObjectMethodExecutor.ExecuteAsync(Object target, Object[] parameters)
   at DotNetCore.CAP.Internal.SubscribeInvoker.ExecuteWithParameterAsync(ObjectMethodExecutor executor, Object class, Object[] parameter)
   at DotNetCore.CAP.Internal.SubscribeInvoker.InvokeAsync(ConsumerContext context, CancellationToken cancellationToken)
   at DotNetCore.CAP.Internal.SubscribeDispatcher.InvokeConsumerMethodAsync(MediumMessage message, ConsumerExecutorDescriptor descriptor, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at DotNetCore.CAP.Internal.SubscribeDispatcher.InvokeConsumerMethodAsync(MediumMessage message, ConsumerExecutorDescriptor descriptor, CancellationToken cancellationToken)
   at DotNetCore.CAP.Internal.SubscribeDispatcher.ExecuteWithoutRetryAsync(MediumMessage message, ConsumerExecutorDescriptor descriptor, CancellationToken cancellationToken)

**Comment by haoas** [comment] 2020-01-10 06:04
v2.6 works well ,v3 throw an exception

**Comment by yang-xiaodong** [comment] 2020-01-10 06:07
duplicate of #473

**Closed by yang-xiaodong** 2020-01-10 06:07 UTC
Labels: duplicate
