### ISSUE TITLE
Question about multiple Kafka clusters

### ISSUE THREAD

**Issue by PoteRii** [dotnetcore/CAP#1580] opened 2024-09-10 15:31 UTC
Hello,
Is there a way to support multiple Kafka clusters at the same time?
Usage scenario: we want to produce business events to one cluster and reporting events to separate cluster

**Comment by yang-xiaodong** [comment] 2024-09-11 01:07
We do not support multiple transports.

Duplicate of https://github.com/dotnetcore/CAP/issues/998

**Closed** 2024-09-14 09:15 UTC
Labels: question
