### ISSUE TITLE
Issue when using both CAP and Hangfire

### ISSUE THREAD

**Issue by rogeryamato** [dotnetcore/CAP#739] opened 2020-12-10 08:29 UTC
Hi:

We found some issue when we using both CAP and Hangfire..

Case 1:

Start project and trigger a job is Hangfire UI error message will show
```
fail: Hangfire.Server.Worker[0]
      10 state change attempt(s) failed due to an exception, moving job to the FailedState
System.InvalidCastException: Unable to cast object of type 'System.Data.SqlClient.SqlConnection' to type 'Microsoft.Data.SqlClient.SqlConnection'.
   at DotNetCore.CAP.SqlServer.Diagnostics.DiagnosticObserver.OnNext(KeyValuePair`2 evt)
   at System.Diagnostics.DiagnosticListener.Write(String name, Object value)
   at System.Data.SqlClient.SqlClientDiagnosticListenerExtensions.WriteTransactionCommitAfter(DiagnosticListener this, Guid operationId, IsolationLevel isolationLevel, SqlConnection connection, String operation)
   at System.Data.SqlClient.SqlTransaction.Commit()
   at Hangfire.SqlServer.SqlServerStorage.<>c__DisplayClass35_0`1.<UseTransaction>b__0(DbConnection connection)
   at Hangfire.SqlServer.SqlServerStorage.UseConnection[T](DbConnection dedicatedConnection, Func`2 func)
   at Hangfire.SqlServer.SqlServerStorage.UseTransaction[T](DbConnection dedicatedConnection, Func`3 func, Nullable`1 isolationLevel)
   at Hangfire.SqlServer.SqlServerStorage.UseTransaction(DbConnection dedicatedConnection, Action`2 action)
   at Hangfire.SqlServer.SqlServerWriteOnlyTransaction.Commit()
   at Hangfire.States.BackgroundJobStateChanger.ChangeState(StateChangeContext context)
   at Hangfire.Server.Worker.TryChangeState(BackgroundProcessContext context, IStorageConnection connection, IFetchedJob fetchedJob, IState state, String[] expectedStates, CancellationToken initializeToken, CancellationToken abortToken)
```

Case 2:
Add UseRecurringJob in Hangfire like:
```
services.AddHangfire(x =>
            {
                x.UseSqlServerStorage(hangfireConnectionString, 
                    new Hangfire.SqlServer.SqlServerStorageOptions 
                    {
                        QueuePollInterval = TimeSpan.FromMinutes(1)
                    });

                 x.UseRecurringJob($"recurringjob.{env}.json");
            });

```
Error is:
```
crit: Microsoft.AspNetCore.Hosting.Diagnostics[6]
      Application startup exception
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.InvalidCastException: Unable to cast object of type 'System.Data.SqlClient.SqlConnection' to type 'Microsoft.Data.SqlClient.SqlConnection'.
   at DotNetCore.CAP.SqlServer.Diagnostics.DiagnosticObserver.OnNext(KeyValuePair`2 evt)
   at System.Diagnostics.DiagnosticListener.Write(String name, Object value)
   at System.Data.SqlClient.SqlClientDiagnosticListenerExtensions.WriteTransactionCommitAfter(DiagnosticListener this, Guid operationId, IsolationLevel isolationLevel, SqlConnection connection, String operation)
   at System.Data.SqlClient.SqlTransaction.Commit()
   at Hangfire.SqlServer.SqlServerStorage.<>c__DisplayClass35_0`1.<UseTransaction>b__0(DbConnection connection)
   at Hangfire.SqlServer.SqlServerStorage.UseConnection[T](DbConnection dedicatedConnection, Func`2 func)
   at Hangfire.SqlServer.SqlServerStorage.UseTransaction[T](DbConnection dedicatedConnection, Func`3 func, Nullable`1 isolationLevel)
   at Hangfire.SqlServer.SqlServerStorage.UseTransaction(DbConnection dedicatedConnection, Action`2 action)
   at Hangfire.SqlServer.SqlServerWriteOnlyTransaction.Commit()
   at Hangfire.RecurringJobManager.AddOrUpdate(String recurringJobId, Job job, String cronExpression, RecurringJobOptions options)
   at Hangfire.RecurringJobManagerExtensions.AddOrUpdate(IRecurringJobManager manager, String recurringJobId, Job job, String cronExpression, TimeZoneInfo timeZone, String queue)
   at lambda_method(Closure )
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at Hangfire.RecurringJobExtensions.RecurringJobRegistry.Register(String recurringJobId, MethodInfo method, String cron, TimeZoneInfo timeZone, String queue)
   at Hangfire.RecurringJobExtensions.RecurringJobRegistry.Register(RecurringJobInfo recurringJobInfo)
   at Hangfire.RecurringJobExtensions.RecurringJobBuilder.Build(Func`1 recurringJobInfoProvider)
   at Hangfire.RecurringJobExtensions.CronJob.AddOrUpdate(IEnumerable`1 recurringJobInfos)
   at Hangfire.RecurringJobExtensions.CronJob.AddOrUpdate(IConfigurationProvider provider)
   at Hangfire.RecurringJobExtensions.CronJob.AddOrUpdate(String jsonFile, Boolean reloadOnChange)
   at Hangfire.RecurringJobExtensions.HangfireExtensions.UseRecurringJob(IGlobalConfiguration configuration, String jsonFile, Boolean reloadOnChange)
   at Walmart.Retail.Buy.Guru.BackgroundDataJob.Startup.<>c__DisplayClass4_0.<ConfigureServices>b__2(IGlobalConfiguration x) in C:\code\GURU.Backend\src\BackgroundDataJob\Startup.cs:line 105
   at Hangfire.HangfireServiceCollectionExtensions.<>c__DisplayClass0_0.<AddHangfire>b__0(IServiceProvider provider, IGlobalConfiguration config)
   at Hangfire.HangfireServiceCollectionExtensions.<>c__DisplayClass1_0.<AddHangfire>b__7(IServiceProvider serviceProvider)
   at AspectCore.Extensions.DependencyInjection.ServiceCollectionToServiceContextExtensions.<>c__DisplayClass4_0.<Replace>b__0(IServiceResolver resolver)
   at AspectCore.DependencyInjection.ServiceCallSiteResolver.<>c__DisplayClass4_0.<ResolveCallback>b__0(ServiceResolver resolver)
   at AspectCore.DependencyInjection.ServiceResolver.<ResolveDefinition>b__12_0(ServiceDefinition d)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at AspectCore.DependencyInjection.ServiceResolver.ResolveDefinition(ServiceDefinition definition)
   at AspectCore.DependencyInjection.ServiceResolver.Resolve(Type serviceType)
   at AspectCore.DependencyInjection.ServiceResolver.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetService[T](IServiceProvider provider)   at Hangfire.HangfireServiceCollectionExtensions.ThrowIfNotConfigured(IServiceProvider serviceProvider)
   at Hangfire.HangfireApplicationBuilderExtensions.UseHangfireServer(IApplicationBuilder app, BackgroundJobServerOptions options, IEnumerable`1 additionalProcesses, JobStorage storage)
   at Walmart.Retail.Buy.Guru.BackgroundDataJob.Startup.Configure(IApplicationBuilder app, IWebHostEnvironment env) in C:\code\GURU.Backend\src\BackgroundDataJob\Startup.cs:line 153
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.AspNetCore.Hosting.ConfigureBuilder.Invoke(Object instance, IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.ConfigureBuilder.<>c__DisplayClass4_0.<Build>b__0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.<>c__DisplayClass13_0.<UseStartup>b__2(IApplicationBuilder app)   at Microsoft.ApplicationInsights.AspNetCore.ApplicationInsightsStartupFilter.<>c__DisplayClass2_0.<Configure>b__0(IApplicationBuilder app)
   at Microsoft.AspNetCore.Mvc.Filters.MiddlewareFilterBuilderStartupFilter.<>c__DisplayClass0_0.<Configure>g__MiddlewareFilterBuilder|0(IApplicationBuilder builder)
   at DotNetCore.CAP.CapStartupFilter.<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder app)
   at Microsoft.AspNetCore.HostFilteringStartupFilter.<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder app)
   at Microsoft.AspNetCore.Hosting.GenericWebHostService.StartAsync(CancellationToken cancellationToken)
info: DotNetCore.CAP.Processor.CapProcessingServer[0]
      Shutting down the processing server...
info: DotNetCore.CAP.Processor.CapProcessingServer[0]
      ### CAP shutdown!

```
By case 1, we can still running this application, By case 2, whole application will shutdown..

We use sql server for CAP and Hangfire. Please help.

**Comment by xiangxiren** [comment] 2020-12-10 12:32
Hangfire.Sqlserver depends on System.Data.SqlClient, while DotNetCore.CAP.SqlServer depends on Microsoft.Data.SqlClient.

**Comment by yang-xiaodong** [comment] 2020-12-10 12:42
Duplicate of #570

**Comment by yang-xiaodong** [comment] 2020-12-10 12:48
Closed, please refer : https://github.com/HangfireIO/Hangfire/issues/1735

**Closed by yang-xiaodong** 2020-12-10 12:48 UTC

**Comment by rogeryamato** [comment] 2020-12-10 15:50
thanks for your help
