### ISSUE TITLE
deserialization error in CAP

### ISSUE THREAD

**Issue by xiaotupansy** [dotnetcore/CAP#441] opened 2019-11-28 12:56 UTC
### Environment:

- .net core 2.2
- CAP 2.6.0
- Mysql 8.0
- RabbitMQ 3.8.0

### Errors:

Today I face a quite strange problem.I use cap to send message. In all environment except one, I get all these code working correctly.But in one enviroment, I got following error :

```
Object of type 'System.String' cannot be converted to type 'System.Boolean'
```
I think this may be caused by some deserialize issue but I didn't do any deserialization in my code.
Hope someone here can help.

Thanks!

#### Dto:

```
public class MessageDto 
    {
        public string Id { get; set; }

        public string MessageContent { get; set; }

        public string DomainType { get; set; }

        public string DomainId { get; set; }

        public bool IsHandled { get; set; }
        
        public string TenantId { get;set; }
    }
```

#### Error Message:

```
{"Id":"5ddfbd9e5763800001f724f3","Timestamp":"2019-11-28T20:29:18.3517113+08:00","Content":"{\"MessageContent\":\"李销售提交了打样单，编号为:DY20191128202842898\",\"DomainType\":\"RFSData\",\"DomainId\":\"1200028743427559424\",\"IsHandled\":false,\"OperationType\":2,\"Id\":\"1200028893378121729\",\"TenantId\":\"1197084043359948800\"}","CallbackName":null,"ExceptionMessage":{"Source":"DotNetCore.CAP","Message":"Object of type 'System.String' cannot be converted to type 'System.Boolean'.","InnerMessage":"Object of type 'System.String' cannot be converted to type 'System.Boolean'."}}
```

#### Receiver:

```
[CapSubscribe("some queue name")]
public async Task PublishAsync(MessageDto messageDto)
{
    // code here
}
```

**Comment by yang-xiaodong** [comment] 2019-12-05 06:17
Hello, I can't reproduce your issue, the data you provided looks like can be deserialized properly

**Comment by xiaotupansy** [comment] 2019-12-05 06:20
Yes. Because it's in correct format.
I think it may be caused by mysql character set but I'm not sure.

**Comment by yang-xiaodong** [comment] 2019-12-05 06:23
OK, Close this question temporarily and  you can always open when needed

**Closed by yang-xiaodong** 2019-12-05 06:23 UTC
