### ISSUE TITLE
Exchange Type Always Set to 'Topic' – Cannot Select Other Types

### ISSUE THREAD

**Issue by HamidrezaTA** [dotnetcore/CAP#1395] opened 2023-08-25 21:15 UTC
It seems that selecting the exchange type is not possible, and the exchange type is always set to 'Topic.' In my development case, I need to subscribe to a routing key that exchange type is 'direct.' I fixed this issue by modifying the exchange type property in the RabbitMQOptions class.

Have any of you encountered a similar problem? If so, how did you resolve it?

**Comment by yang-xiaodong** [comment] 2023-08-26 14:02
Duplicate of #930

**Closed by yang-xiaodong** 2023-08-26 14:02 UTC
Labels: duplicate
