### ISSUE TITLE
【重新加入队列】报错

### ISSUE THREAD

**Issue by wilsonliu78** [dotnetcore/CAP#216] opened 2018-10-17 07:39 UTC
fail: Microsoft.AspNetCore.Server.Kestrel[13]
      => ConnectionId:0HLHJVUELVB0K => RequestId:0HLHJVUELVB0K:00000002 RequestPath:/cap/received/requeue
      Connection id "0HLHJVUELVB0K", Request id "0HLHJVUELVB0K:00000002": An unhandled exception was thrown by the application.
System.OverflowException: Value was either too large or too small for an Int32.
   at System.Number.ParseInt32(String s, NumberStyles style, NumberFormatInfo info)
   at DotNetCore.CAP.Dashboard.BatchCommandDispatcher.<Dispatch>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at DotNetCore.CAP.Dashboard.GatewayProxy.GatewayProxyMiddleware.<Invoke>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.<ProcessRequests>d__186`1.MoveNext()

**Comment by yang-xiaodong** [comment] 2018-10-17 07:41
Duplicate of #205

**Closed by yang-xiaodong** 2018-10-17 07:41 UTC
Labels: duplicate
