### ISSUE TITLE
Clarification on OperationCanceledException Handling in Cap

### ISSUE THREAD

**Issue by MahmoudSamir101** [dotnetcore/CAP#1610] opened 2024-11-12 08:25 UTC
Hi,

I wanted to clarify an issue I encountered regarding how Cap handles the OperationCanceledException raised from the ConsumerMethod in the source code.

In my case, this handling leads to unexpected behavior. The consumer method makes a call to an external API, which was canceled due to a timeout from the HTTP client. This resulted in a TaskCanceledException being thrown, which Cap treats as an OperationCanceledException. Consequently, the message is marked as a success, which is not the behavior I expected. Instead, it should fail and be retried.

Is this behavior intended by design, even in cases involving timeout exceptions? 

https://github.com/dotnetcore/CAP/blob/2f8080e8213a68d5d37a6616dcf7d30eae1c4c07/src/DotNetCore.CAP/Internal/ISubscribeExector.Default.cs#L199

**Comment by yang-xiaodong** [comment] 2024-11-12 12:25
Hi,

This is a duplicate of #1368,  check out the docs.

![image](https://github.com/user-attachments/assets/b5769669-5040-4f4a-b201-6ed5d34b4190)

**Comment by MahmoudSamir101** [comment] 2024-11-12 12:31
Noted, Thanks. 👍

**Closed** 2024-11-14 01:54 UTC
