### ISSUE TITLE
Add new option for parallel publish send.

### ISSUE THREAD

**Issue by maisa92** [dotnetcore/CAP#1540] opened 2024-06-06 12:56 UTC
When we enable the `EnablePublishParallelSend` option, our application crashes under high load.

Is it possible to add an option to control the thread count for parallel sending? like it is done on the subscriber side `SubscriberParallelExecuteThreadCount`.

I am referring to [issue #1513](https://github.com/dotnetcore/CAP/issues/1513) as a benchmark, and I believe a similar improvement would help us resolve this issue.

**Comment by yang-xiaodong** [comment] 2024-06-11 13:19
Hello @maisa92 ,

I need some time to determine the cause of the application crash because I didn't observe this issue in my previous benchmarks. Unlike consumption, publishing messages is a short-term task, which is well-suited for .NET thread pool tasks.

Could you share more information? For example, was it running in Docker and got killed due to exceeding memory or CPU limits, or was there another reason? Any details you can share would be greatly appreciated.

**Comment by yang-xiaodong** [comment] 2024-06-23 11:39
Fixed in version 8.2.0. 

Place tasks batches into thread pool when turning on `EnablePublishParallelSend`

**Closed by yang-xiaodong** 2024-06-23 11:39 UTC
Labels: enhancement, fixed
