### ISSUE TITLE
RabbitMQ cannot  ACK messages in docker compose network

### ISSUE THREAD

**Issue by usama-azakaw** [dotnetcore/CAP#584] opened 2020-06-11 08:20 UTC
We are facing an issue with CAP & RabbitMQ where messages are there in the queue with Unacked and there's nothing the Received table as well. There are no connection related issues there in the log as well. Please refer the image below

![image](https://user-images.githubusercontent.com/53209642/84362178-dfdac500-abdd-11ea-8c22-d42cc9aae400.png)

**Comment by usama-azakaw** [comment] 2020-06-11 09:14
@yang-xiaodong looking for your help here

**Comment by yang-xiaodong** [comment] 2020-06-11 09:15
Please provider your environemnt and configuraiton

**Comment by usama-azakaw** [comment] 2020-06-11 10:26
RabbitMQ configurations:
**RABBITMQ_NODE_TYPE=stats
RABBITMQ_NODE_NAME=rabbit@rabbitmq-stats
#RABBITMQ_DISK_FREE_LIMIT=1000000000**

below is how our RabbitMQ service looks like in docker-compose

  **rabbitmq-stats:
    image: bitnami/rabbitmq:${rabbitmq_version}
    env_file:
      - rabbitmq-env-variables.env
    volumes:
      - ./rabbitmqstats_data:/bitnami/
    ports:
      - "15672:15672"
      - "5672:5672"
    restart: unless-stopped

  rabbitmq-disk:
    image: bitnami/rabbitmq:${rabbitmq_version}
    depends_on:
      - "rabbitmq-stats"
    env_file:
      - rabbitmq.disk-env-variables.env
    volumes:
      - ./rabbitmqdisk_data:/bitnami/
    restart: unless-stopped**

**Comment by usama-azakaw** [comment] 2020-06-11 10:28
We are using docker-compose to run our services & rabbitmq. We are able to publish successfully but messages are not getting consumed from queue although I can see the messages in the queue waiting for ACK.

We are using the latest version of CAP 3.0.4

**Comment by usama-azakaw** [comment] 2020-06-11 11:19
Rabbit MQ server version is 3.8.1

**Comment by usama-azakaw** [comment] 2020-06-11 11:19
@yang-xiaodong

**Comment by yang-xiaodong** [comment] 2020-06-12 03:56
Hello, I cannot reproduce this issue. Can this issue be reproduced in the local environment?

**Comment by usama-azakaw** [comment] 2020-06-14 10:37
Somehow this is related to docker-compose network issue , Services are able to successfully publish events but it seems like RabbitMQ is not able to send messages to subscribers.

**Comment by usama-azakaw** [comment] 2020-06-14 10:38
and this is only happening when you run services and RabbitMQ using docker-compose with default network.

**Comment by usama-azakaw** [comment] 2020-06-14 12:03
@yang-xiaodong the issue looks similar to issue #329

**Comment by usama-azakaw** [comment] 2020-06-15 10:22
We downgraded the CAP version back to 2.6 and then it works. Seems like this has something to do with the latest version 3.0.4

**Comment by yang-xiaodong** [comment] 2020-10-23 15:06
Close this issue, if anyone reproduce it again, will reopen it

**Closed by yang-xiaodong** 2020-10-23 15:06 UTC
Labels: backlog
